# Generated by Django 5.0.7 on 2024-07-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obituaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obituary',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
